/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tcp_calculate_app.h"

bool_t
xdr_data_in (XDR *xdrs, data_in *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->array.array_val, (u_int *) &objp->array.array_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ar_length))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->x_multiplier))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_data_out (XDR *xdrs, data_out *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (1 + ( 2 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->array_min_max, 2,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ar_length))
				 return FALSE;

		} else {
		{
			register int *genp;

			for (i = 0, genp = objp->array_min_max;
				i < 2; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		IXDR_PUT_LONG(buf, objp->ar_length);
		}
		 if (!xdr_array (xdrs, (char **)&objp->multi_array.multi_array_val, (u_int *) &objp->multi_array.multi_array_len, ~0,
			sizeof (double), (xdrproc_t) xdr_double))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (1 + ( 2 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->array_min_max, 2,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ar_length))
				 return FALSE;

		} else {
		{
			register int *genp;

			for (i = 0, genp = objp->array_min_max;
				i < 2; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		objp->ar_length = IXDR_GET_LONG(buf);
		}
		 if (!xdr_array (xdrs, (char **)&objp->multi_array.multi_array_val, (u_int *) &objp->multi_array.multi_array_len, ~0,
			sizeof (double), (xdrproc_t) xdr_double))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->array_min_max, 2,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ar_length))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->multi_array.multi_array_val, (u_int *) &objp->multi_array.multi_array_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}
