/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TCP_CALCULATE_APP_H_RPCGEN
#define _TCP_CALCULATE_APP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data_in {
	struct {
		u_int array_len;
		int *array_val;
	} array;
	int ar_length;
	double x_multiplier;
};
typedef struct data_in data_in;

struct data_out {
	int array_min_max[2];
	int ar_length;
	struct {
		u_int multi_array_len;
		double *multi_array_val;
	} multi_array;
};
typedef struct data_out data_out;

#define PROG 0x30090949
#define VER1 1

#if defined(__STDC__) || defined(__cplusplus)
#define minmax 1
extern  data_out * minmax_1(data_in *, CLIENT *);
extern  data_out * minmax_1_svc(data_in *, struct svc_req *);
#define avg 2
extern  double * avg_1(data_in *, CLIENT *);
extern  double * avg_1_svc(data_in *, struct svc_req *);
#define multiply 3
extern  data_out * multiply_1(data_in *, CLIENT *);
extern  data_out * multiply_1_svc(data_in *, struct svc_req *);
extern int prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define minmax 1
extern  data_out * minmax_1();
extern  data_out * minmax_1_svc();
#define avg 2
extern  double * avg_1();
extern  double * avg_1_svc();
#define multiply 3
extern  data_out * multiply_1();
extern  data_out * multiply_1_svc();
extern int prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data_in (XDR *, data_in*);
extern  bool_t xdr_data_out (XDR *, data_out*);

#else /* K&R C */
extern bool_t xdr_data_in ();
extern bool_t xdr_data_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TCP_CALCULATE_APP_H_RPCGEN */
